/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package it.iiscastelli.tama.ui;

import javax.swing.ImageIcon;

/**
 *
 * @author Ely
 */
public class FinestraMessaggio extends javax.swing.JDialog {

    /**
     * Creates new form FinestraErrore
     */
    public FinestraMessaggio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public void setTitolo(String titolo) {
        lblTitolo.setText(titolo);
    }

    public void setMessaggio(String messaggio) {
        txtMessaggio.setText(messaggio);
    }

    public void setIcona(String nomeIcona) {
        lblTamaIcona.setIcon(new ImageIcon(nomeIcona));
    }

    public void setTestoPulsante(String testo) {
        btnChiudi.setText(testo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondo = new javax.swing.JPanel();
        lblTamaIcona = new javax.swing.JLabel();
        lblTitolo = new javax.swing.JLabel();
        btnChiudi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessaggio = new it.iiscastelli.tama.ui.custom.TextPaneCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Info");
        setResizable(false);

        sfondo.setBackground(new java.awt.Color(255, 206, 209));

        lblTamaIcona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/iis/tama/assets/Tamagotchi32.png"))); // NOI18N

        lblTitolo.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Titolo");

        btnChiudi.setBackground(new java.awt.Color(201, 75, 152));
        btnChiudi.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnChiudi.setForeground(new java.awt.Color(255, 255, 255));
        btnChiudi.setText("CHIUDI");
        btnChiudi.setBorderPainted(false);
        btnChiudi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChiudi.setFocusPainted(false);
        btnChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiudiActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtMessaggio.setEditable(false);
        txtMessaggio.setBackground(new java.awt.Color(255, 206, 209));
        txtMessaggio.setBorder(null);
        txtMessaggio.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        txtMessaggio.setText("Messaggio");
        txtMessaggio.setFocusable(false);
        jScrollPane1.setViewportView(txtMessaggio);

        javax.swing.GroupLayout sfondoLayout = new javax.swing.GroupLayout(sfondo);
        sfondo.setLayout(sfondoLayout);
        sfondoLayout.setHorizontalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitolo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoLayout.createSequentialGroup()
                        .addComponent(lblTamaIcona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(btnChiudi))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        sfondoLayout.setVerticalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChiudi)
                    .addComponent(lblTamaIcona, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiudiActionPerformed
        dispose();
    }//GEN-LAST:event_btnChiudiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiudi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTamaIcona;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel sfondo;
    private it.iiscastelli.tama.ui.custom.TextPaneCustom txtMessaggio;
    // End of variables declaration//GEN-END:variables
}
