package it.iiscastelli.tama.ui;

import it.iiscastelli.tama.data.TamaTriste;
import it.iiscastelli.tama.data.TamaGordo;
import it.iiscastelli.tama.data.Tamagotchi;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author 93007327
 */
public class FinestraConfigurazione extends javax.swing.JDialog {

    private static final int TIPO_NORMALE = 0;
    private static final int TIPO_TRISTE = 1;
    private static final int TIPO_GORDO = 2;

    private int tipoTamaAttuale;

    private FinestraPrincipale padre;
    private String[] immagini;

    /**
     * Creates new form FinestraConfigurazione
     *
     * @param parent
     * @param modal
     */
    public FinestraConfigurazione(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        padre = (FinestraPrincipale) parent;
        setLocationRelativeTo(parent);
        lblTipoTama.setText("TAMAGOTCHI");
        immagini = new String[3];
        immagini[TIPO_NORMALE] = "src/it/iis/tama/assets/Tamagotchi96.png";
        immagini[TIPO_TRISTE] = "src/it/iis/tama/assets/TamaTriste96.png";
        immagini[TIPO_GORDO] = "src/it/iis/tama/assets/TamaGordo96.png";
        tipoTamaAttuale = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeTama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnPrecedente = new javax.swing.JButton();
        btnSuccessivo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnIndietro = new javax.swing.JButton();
        lblTipoTama = new javax.swing.JLabel();
        sliderAffetto = new javax.swing.JSlider();
        sliderSazieta = new javax.swing.JSlider();
        lblAffetto = new javax.swing.JLabel();
        lblSazieta = new javax.swing.JLabel();
        iconaTama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuovo Tamagotchi");
        setResizable(false);

        sfondo.setBackground(new java.awt.Color(255, 246, 224));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel1.setText("Nome");

        txtNomeTama.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        txtNomeTama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 206, 209), 2, true));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setText("Tipo Tamagotchi");

        btnPrecedente.setBackground(new java.awt.Color(255, 144, 183));
        btnPrecedente.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnPrecedente.setForeground(new java.awt.Color(255, 255, 255));
        btnPrecedente.setText("<");
        btnPrecedente.setBorderPainted(false);
        btnPrecedente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrecedente.setEnabled(false);
        btnPrecedente.setFocusPainted(false);
        btnPrecedente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedenteActionPerformed(evt);
            }
        });

        btnSuccessivo.setBackground(new java.awt.Color(255, 144, 183));
        btnSuccessivo.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnSuccessivo.setForeground(new java.awt.Color(255, 255, 255));
        btnSuccessivo.setText(">");
        btnSuccessivo.setBorderPainted(false);
        btnSuccessivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuccessivo.setFocusPainted(false);
        btnSuccessivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuccessivoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setText("Affetto iniziale");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel4.setText("Sazietà iniziale");

        btnOk.setBackground(new java.awt.Color(255, 144, 183));
        btnOk.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("Ok");
        btnOk.setBorderPainted(false);
        btnOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOk.setFocusPainted(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnIndietro.setBackground(new java.awt.Color(255, 144, 183));
        btnIndietro.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnIndietro.setForeground(new java.awt.Color(255, 255, 255));
        btnIndietro.setText("Indietro");
        btnIndietro.setBorderPainted(false);
        btnIndietro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIndietro.setFocusPainted(false);
        btnIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndietroActionPerformed(evt);
            }
        });

        lblTipoTama.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        lblTipoTama.setForeground(new java.awt.Color(255, 99, 162));
        lblTipoTama.setText("Tipo Tama");

        sliderAffetto.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        sliderAffetto.setForeground(new java.awt.Color(255, 99, 162));
        sliderAffetto.setMinimum(1);
        sliderAffetto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sliderAffetto.setFocusable(false);
        sliderAffetto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderAffettoMouseDragged(evt);
            }
        });

        sliderSazieta.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        sliderSazieta.setForeground(new java.awt.Color(255, 99, 162));
        sliderSazieta.setMaximum(99);
        sliderSazieta.setMinimum(1);
        sliderSazieta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sliderSazieta.setFocusable(false);
        sliderSazieta.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderSazietaMouseDragged(evt);
            }
        });

        lblAffetto.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        lblAffetto.setText("50");

        lblSazieta.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        lblSazieta.setText("50");

        iconaTama.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        iconaTama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconaTama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/iis/tama/assets/Tamagotchi96.png"))); // NOI18N

        javax.swing.GroupLayout sfondoLayout = new javax.swing.GroupLayout(sfondo);
        sfondo.setLayout(sfondoLayout);
        sfondoLayout.setHorizontalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(lblTipoTama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sfondoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndietro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOk)
                                .addContainerGap())
                            .addGroup(sfondoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(iconaTama)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(txtNomeTama)))
                        .addGap(0, 0, 0)
                        .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoLayout.createSequentialGroup()
                                .addComponent(sliderSazieta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSazieta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sfondoLayout.createSequentialGroup()
                                .addComponent(sliderAffetto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAffetto)))
                        .addGap(84, 84, 84))))
            .addGroup(sfondoLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btnPrecedente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuccessivo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sfondoLayout.setVerticalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeTama, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addComponent(iconaTama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrecedente)
                            .addComponent(btnSuccessivo))
                        .addGap(18, 18, 18))
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTipoTama)))
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sliderAffetto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAffetto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sliderSazieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSazieta))
                .addGap(11, 11, 11)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnIndietro))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (txtNomeTama.getText().isBlank()) {
            FinestraMessaggio errore = new FinestraMessaggio(padre, true);
            errore.setTitolo("Errore!");
            errore.setMessaggio("Il nome non può essere vuoto");
            errore.setIcona("src/it/iis/tama/assets/TamaTriste32.png");
            errore.setVisible(true);
            return;
        }
        padre.aggiungiTama(creaTama());
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private Tamagotchi creaTama() {
        String nome = txtNomeTama.getText();
        int affettoIniziale = sliderAffetto.getValue();
        int sazietaIniziale = sliderSazieta.getValue();
        return switch (tipoTamaAttuale) {
            case TIPO_TRISTE ->
                new TamaTriste(nome, sazietaIniziale);
            case TIPO_GORDO ->
                new TamaGordo(nome, sazietaIniziale);
            default ->
                new Tamagotchi(nome, affettoIniziale, sazietaIniziale);
        };
    }

    private void sliderAffettoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderAffettoMouseDragged
        lblAffetto.setText(String.valueOf(sliderAffetto.getValue()));
    }//GEN-LAST:event_sliderAffettoMouseDragged

    private void sliderSazietaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderSazietaMouseDragged
        lblSazieta.setText(String.valueOf(sliderSazieta.getValue()));
    }//GEN-LAST:event_sliderSazietaMouseDragged

    private void btnIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndietroActionPerformed
        dispose();
    }//GEN-LAST:event_btnIndietroActionPerformed

    private void btnSuccessivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuccessivoActionPerformed
        tipoTamaAttuale++;
        btnPrecedente.setEnabled(true);
        if (tipoTamaAttuale == immagini.length - 1) {
            btnSuccessivo.setEnabled(false);
        }
        aggiornaImmagine();
        aggiornaTipoTama();
        aggiornaAffetto();
    }//GEN-LAST:event_btnSuccessivoActionPerformed

    private void aggiornaImmagine() {
        iconaTama.setIcon(new ImageIcon(immagini[tipoTamaAttuale]));
    }

    private void aggiornaTipoTama() {
        switch (tipoTamaAttuale) {
            case TIPO_TRISTE:
                lblTipoTama.setText("TAMATRISTE");
                break;
            case TIPO_GORDO:
                lblTipoTama.setText("TAMAGORDO");
                break;
            default:
                lblTipoTama.setText("TAMAGOTCHI");
                break;
        }
    }

    private void aggiornaAffetto() {
        switch (tipoTamaAttuale) {
            case TIPO_TRISTE:
                sliderAffetto.setMinimum(Tamagotchi.MIN_AFFETTO);
                sliderAffetto.setValue(Tamagotchi.MIN_AFFETTO);
                lblAffetto.setText(String.valueOf(Tamagotchi.MIN_AFFETTO));
                sliderAffetto.setEnabled(false);
                break;
            case TIPO_GORDO:
                sliderAffetto.setValue(Tamagotchi.MAX_AFFETTO);
                lblAffetto.setText(String.valueOf(Tamagotchi.MAX_AFFETTO));
                sliderAffetto.setEnabled(false);
                break;
            default:
                sliderAffetto.setValue(50);
                lblAffetto.setText("50");
                sliderAffetto.setEnabled(true);
                break;
        }
    }

    private void btnPrecedenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedenteActionPerformed
        tipoTamaAttuale--;
        btnSuccessivo.setEnabled(true);
        if (tipoTamaAttuale == 0) {
            btnPrecedente.setEnabled(false);
        }
        aggiornaImmagine();
        aggiornaTipoTama();
        aggiornaAffetto();
    }//GEN-LAST:event_btnPrecedenteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIndietro;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPrecedente;
    private javax.swing.JButton btnSuccessivo;
    private javax.swing.JLabel iconaTama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAffetto;
    private javax.swing.JLabel lblSazieta;
    private javax.swing.JLabel lblTipoTama;
    private javax.swing.JPanel sfondo;
    private javax.swing.JSlider sliderAffetto;
    private javax.swing.JSlider sliderSazieta;
    private javax.swing.JTextField txtNomeTama;
    // End of variables declaration//GEN-END:variables
}
