package it.iiscastelli.tama.ui;

import com.formdev.flatlaf.FlatLightLaf;
import it.iiscastelli.tama.data.TamaZoo;
import it.iiscastelli.tama.data.io.Slot;
import it.iiscastelli.tama.data.io.SlotPartita;
import it.iiscastelli.tama.data.io.SlotVuoto;
import it.iiscastelli.tama.data.save.Operazione;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
public class FinestraMenu extends javax.swing.JDialog {

    private JFrame padre;
    private TamaZoo zoo;
    private Slot[] slots;

    /**
     * Creates new form FinestraIniziale
     */
    public FinestraMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        padre = (JFrame) parent;
        initComponents();
        inizializza();
    }

    private void inizializza() {
        setLocationRelativeTo(padre);
        btnSalva.setVisible(false);
        btnChiudi.setVisible(false);
        preparaSlots();
    }

    private void preparaSlots() {
        slots = new Slot[4];
        for (int i = 0; i < slots.length; i++) {
            File fileSlot = new File("slot" + (i + 1) + ".sav");
            Slot slot;
            if (fileSlot.exists()) {
                try {
                    slot = new SlotPartita(i + 1, fileSlot);
                } catch (IOException ex) {
                    slot = new SlotVuoto(i + 1);
                }
            } else {
                slot = new SlotVuoto(i + 1);
            }
            slots[i] = slot;
        }
    }

    public void setZoo(TamaZoo zoo) {
        this.zoo = zoo;
        btnSalva.setVisible(zoo != null);
        btnChiudi.setVisible(zoo != null);
    }

    public JFrame getPadre() {
        return padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sfondo = new javax.swing.JPanel();
        btnNuovaPartita = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();
        btnCarica = new javax.swing.JButton();
        btnChiudi = new javax.swing.JButton();
        btnEsci = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menù");
        setMinimumSize(new java.awt.Dimension(250, 250));
        setResizable(false);
        setSize(new java.awt.Dimension(250, 250));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        sfondo.setBackground(new java.awt.Color(255, 206, 209));
        sfondo.setLayout(new java.awt.GridBagLayout());

        btnNuovaPartita.setBackground(new java.awt.Color(201, 75, 152));
        btnNuovaPartita.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnNuovaPartita.setForeground(new java.awt.Color(255, 255, 255));
        btnNuovaPartita.setText("Nuova Partita");
        btnNuovaPartita.setBorderPainted(false);
        btnNuovaPartita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuovaPartita.setFocusPainted(false);
        btnNuovaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuovaPartitaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        sfondo.add(btnNuovaPartita, gridBagConstraints);

        btnSalva.setBackground(new java.awt.Color(201, 75, 152));
        btnSalva.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnSalva.setForeground(new java.awt.Color(255, 255, 255));
        btnSalva.setText("Salva Partita");
        btnSalva.setBorderPainted(false);
        btnSalva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalva.setFocusPainted(false);
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        sfondo.add(btnSalva, gridBagConstraints);

        btnCarica.setBackground(new java.awt.Color(201, 75, 152));
        btnCarica.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnCarica.setForeground(new java.awt.Color(255, 255, 255));
        btnCarica.setText("Carica Partita");
        btnCarica.setBorderPainted(false);
        btnCarica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarica.setFocusPainted(false);
        btnCarica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        sfondo.add(btnCarica, gridBagConstraints);

        btnChiudi.setBackground(new java.awt.Color(201, 75, 152));
        btnChiudi.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnChiudi.setForeground(new java.awt.Color(255, 255, 255));
        btnChiudi.setText("Chiudi");
        btnChiudi.setBorderPainted(false);
        btnChiudi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChiudi.setFocusPainted(false);
        btnChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiudiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        sfondo.add(btnChiudi, gridBagConstraints);

        btnEsci.setBackground(new java.awt.Color(201, 75, 152));
        btnEsci.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnEsci.setForeground(new java.awt.Color(255, 255, 255));
        btnEsci.setText("Esci");
        btnEsci.setBorderPainted(false);
        btnEsci.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsci.setFocusPainted(false);
        btnEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsciActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        sfondo.add(btnEsci, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuovaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuovaPartitaActionPerformed
        FinestraPrincipale finestra = new FinestraPrincipale();
        finestra.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNuovaPartitaActionPerformed

    private void btnEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsciActionPerformed
        if (padre == null) {
            dispose();
        } else {
            padre.dispose();
        }
    }//GEN-LAST:event_btnEsciActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        FinestraSalvataggi finestra = new FinestraSalvataggi(padre, true, Operazione.SALVATAGGIO);
        finestra.setZoo(zoo);
        finestra.setSlots(slots);
        finestra.setPadre(this);
        setVisible(false);
        finestra.setVisible(true);
    }//GEN-LAST:event_btnSalvaActionPerformed

    private void btnCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaActionPerformed
        FinestraSalvataggi finestra = new FinestraSalvataggi(padre, true, Operazione.CARICAMENTO);
        finestra.setZoo(zoo);
        finestra.setSlots(slots);
        finestra.setPadre(this);
        setVisible(false);
        finestra.setVisible(true);

    }//GEN-LAST:event_btnCaricaActionPerformed

    private void btnChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiudiActionPerformed
        padre.setEnabled(true);
        dispose();
    }//GEN-LAST:event_btnChiudiActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (padre != null) {
            padre.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(FlatLightLaf.class.getName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinestraMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinestraMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinestraMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinestraMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinestraMenu(null, false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarica;
    private javax.swing.JButton btnChiudi;
    private javax.swing.JButton btnEsci;
    private javax.swing.JButton btnNuovaPartita;
    private javax.swing.JButton btnSalva;
    private javax.swing.JPanel sfondo;
    // End of variables declaration//GEN-END:variables
}
