package it.iiscastelli.tama.ui;

import it.iiscastelli.tama.data.TamaZoo;
import it.iiscastelli.tama.data.Tamagotchi;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Ely
 */
public class FinestraPrincipale extends javax.swing.JFrame implements ListSelectionListener {

    private TamaZoo zoo;

    public FinestraPrincipale() {
        initComponents();
        inizializza();
    }

    private void inizializza() {
        zoo = new TamaZoo();
        tabellaTamaZoo.setZoo(zoo);
        tabellaTamaZoo.addSelectionListener(this);
    }

    public void aggiungiTama(Tamagotchi tama) {
        zoo.aggiungi(tama);
        btnAggiungi.setEnabled(zoo.conta() < 6);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        btnElimina.setEnabled(tabellaTamaZoo.getSelectedRow() >= 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondo = new javax.swing.JPanel();
        btnAggiungi = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnIndietro = new javax.swing.JButton();
        btnConferma = new javax.swing.JButton();
        tabellaTamaZoo = new it.iiscastelli.tama.ui.TabellaTamaZoo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TamaZoo");
        setResizable(false);

        sfondo.setBackground(new java.awt.Color(255, 246, 224));

        btnAggiungi.setBackground(new java.awt.Color(255, 144, 183));
        btnAggiungi.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnAggiungi.setForeground(new java.awt.Color(255, 255, 255));
        btnAggiungi.setText("Aggiungi");
        btnAggiungi.setBorderPainted(false);
        btnAggiungi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiActionPerformed(evt);
            }
        });

        btnElimina.setBackground(new java.awt.Color(255, 144, 183));
        btnElimina.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnElimina.setForeground(new java.awt.Color(255, 255, 255));
        btnElimina.setText("Rimuovi");
        btnElimina.setBorderPainted(false);
        btnElimina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnElimina.setEnabled(false);
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });

        btnIndietro.setBackground(new java.awt.Color(255, 144, 183));
        btnIndietro.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnIndietro.setForeground(new java.awt.Color(255, 255, 255));
        btnIndietro.setText("Indietro");
        btnIndietro.setBorderPainted(false);
        btnIndietro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndietroActionPerformed(evt);
            }
        });

        btnConferma.setBackground(new java.awt.Color(255, 144, 183));
        btnConferma.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnConferma.setForeground(new java.awt.Color(255, 255, 255));
        btnConferma.setText("Conferma");
        btnConferma.setBorderPainted(false);
        btnConferma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConferma.setEnabled(false);
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sfondoLayout = new javax.swing.GroupLayout(sfondo);
        sfondo.setLayout(sfondoLayout);
        sfondoLayout.setHorizontalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIndietro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConferma))
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addComponent(btnAggiungi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnElimina))
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addComponent(tabellaTamaZoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sfondoLayout.setVerticalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAggiungi)
                    .addComponent(btnElimina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabellaTamaZoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConferma)
                    .addComponent(btnIndietro))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiActionPerformed
        FinestraConfigurazione configurazione = new FinestraConfigurazione(this, true);
        configurazione.setVisible(true);
        btnConferma.setEnabled(true);
    }//GEN-LAST:event_btnAggiungiActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        zoo.elimina(tabellaTamaZoo.getSelectedRow());
        btnConferma.setEnabled(zoo.conta() > 0);
        btnAggiungi.setEnabled(true);
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
        FinestraGioco gioco = new FinestraGioco(zoo);
        gioco.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConfermaActionPerformed

    private void btnIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndietroActionPerformed
        FinestraMenu menu = new FinestraMenu(null, false);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIndietroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JButton btnConferma;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnIndietro;
    private javax.swing.JPanel sfondo;
    private it.iiscastelli.tama.ui.TabellaTamaZoo tabellaTamaZoo;
    // End of variables declaration//GEN-END:variables

}
