package it.iiscastelli.tama.ui;

import it.iiscastelli.tama.data.Tamagotchi;
import it.iiscastelli.tama.ui.custom.Colore;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.ImageIcon;
import javax.swing.JProgressBar;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
public class PanelTama extends javax.swing.JPanel implements PropertyChangeListener {

    private Tamagotchi tama;

    /**
     * Creates new form PanelTama
     */
    public PanelTama() {
        initComponents();

    }

    public void setTama(Tamagotchi tama) {
        if (this.tama != null) {
            this.tama.removePropertyChangeListener(this);
        }
        this.tama = tama;
        if (tama != null) {
            this.tama.addPropertyChangeListener(this);
            lblNomeTama.setText(tama.getNome());
            aggiornaAffetto(tama.getAffetto());
            aggiornaSazieta(tama.getSazieta());
            lblTamaIcon.setIcon(new ImageIcon(tama.getNomeIcona32()));
            aggiornaStato();
        }
    }

    private void aggiornaStato() {
        lblTriste.setVisible(tama.infelice());
        if (tama.morto()) {
            lblTamaIcon.setIcon(new ImageIcon("src/it/iis/tama/assets/TamaMorto32.png"));
        }
    }

    private void aggiornaAffetto(int affetto) {
        aggiornaProgressBar(barAffetto, affetto);
        lblAffetto.setText(String.valueOf(affetto));
    }

    private void aggiornaSazieta(int sazieta) {
        aggiornaProgressBar(barSazieta, sazieta);
        lblSazieta.setText(String.valueOf(sazieta));
    }

    private void aggiornaProgressBar(JProgressBar progressBar, int valore) {
        progressBar.setValue(valore);
        if (valore < 0.15 * progressBar.getMaximum()) {
            progressBar.setForeground(Colore.FRENCH_PINK);
        } else if (valore < 0.5 * progressBar.getMaximum()) {
            progressBar.setForeground(Colore.LOVE_FUMES);
        } else {
            progressBar.setForeground(Colore.LUNATIC_SKY_DANCER);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeTama = new javax.swing.JLabel();
        barAffetto = new javax.swing.JProgressBar();
        barSazieta = new javax.swing.JProgressBar();
        lblTamaIcon = new javax.swing.JLabel();
        lblAffetto = new javax.swing.JLabel();
        lblSazieta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTriste = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 246, 224));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblNomeTama.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        lblNomeTama.setForeground(new java.awt.Color(255, 99, 162));
        lblNomeTama.setText("Nome");

        barAffetto.setBackground(new java.awt.Color(112, 116, 157));
        barAffetto.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        barAffetto.setForeground(new java.awt.Color(107, 255, 164));
        barAffetto.setBorderPainted(false);
        barAffetto.setFocusable(false);

        barSazieta.setBackground(new java.awt.Color(112, 116, 157));
        barSazieta.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        barSazieta.setForeground(new java.awt.Color(107, 255, 164));
        barSazieta.setBorderPainted(false);
        barSazieta.setFocusable(false);

        lblTamaIcon.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        lblTamaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/iis/tama/assets/Tamagotchi32.png"))); // NOI18N

        lblAffetto.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblAffetto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAffetto.setText("100");

        lblSazieta.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblSazieta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSazieta.setText("100");

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/iis/tama/assets/affetto16.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/iis/tama/assets/biscotto16.png"))); // NOI18N

        lblTriste.setBackground(new java.awt.Color(255, 99, 162));
        lblTriste.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        lblTriste.setForeground(new java.awt.Color(255, 255, 255));
        lblTriste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTriste.setText("!");
        lblTriste.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeTama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTriste, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barSazieta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTamaIcon)
                            .addComponent(lblSazieta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barAffetto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAffetto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTamaIcon)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNomeTama)
                        .addComponent(lblTriste)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(barAffetto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAffetto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barSazieta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSazieta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        int valore = (int) evt.getNewValue();
        switch (evt.getPropertyName()) {
            case Tamagotchi.PROP_AFFETTO ->
                aggiornaAffetto(valore);
            case Tamagotchi.PROP_SAZIETA ->
                aggiornaSazieta(valore);
        }
        aggiornaStato();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barAffetto;
    private javax.swing.JProgressBar barSazieta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAffetto;
    private javax.swing.JLabel lblNomeTama;
    private javax.swing.JLabel lblSazieta;
    private javax.swing.JLabel lblTamaIcon;
    private javax.swing.JLabel lblTriste;
    // End of variables declaration//GEN-END:variables

}
