/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package it.iiscastelli.tama.ui;

import it.iiscastelli.tama.data.Tamagotchi;
import it.iiscastelli.tama.ui.custom.Colore;
import it.iiscastelli.tama.util.ScritturaLenta;
import it.iiscastelli.tama.util.StatoZooListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.ImageIcon;
import javax.swing.JProgressBar;

public class PanelTamaScelto extends javax.swing.JPanel implements PropertyChangeListener {

    private Tamagotchi tama;
    private ScritturaLenta scrittore;
    private StatoZooListener listener;

    public PanelTamaScelto() {
        initComponents();
    }

    public void setTama(Tamagotchi tama) {
        if (this.tama != null) {
            this.tama.removePropertyChangeListener(this);
        }
        this.tama = tama;
        if (tama != null) {
            this.tama.addPropertyChangeListener(this);
            lblNomeTama.setText(tama.getNome());
            aggiornaAffetto(tama.getAffetto());
            aggiornaSazieta(tama.getSazieta());
            lblTamaSceltoIcon.setIcon(new ImageIcon(tama.getNomeIcona96()));
            aggiornaStato(true);
        }
    }

    public void setQuantita(int quantita) {
        sliderQuantita.setValue(quantita);
        lblQuantita.setText(String.valueOf(quantita));
    }

    public void setScrittore(ScritturaLenta scrittore) {
        this.scrittore = scrittore;
    }

    public void setStatoZooListener(StatoZooListener listener) {
        this.listener = listener;
    }

    private void aggiornaAffetto(int affetto) {
        aggiornaProgressBar(barAffetto, affetto);
        lblAffetto.setText(String.valueOf(affetto));
    }

    private void aggiornaSazieta(int sazieta) {
        aggiornaProgressBar(barSazieta, sazieta);
        lblSazieta.setText(String.valueOf(sazieta));
    }

    private void aggiornaStato(boolean iniziale) {
        lblTriste.setVisible(tama.infelice());
        btnDaiBiscotti.setEnabled(!tama.morto());
        btnDaiCarezze.setEnabled(!tama.morto());
        if (tama.morto()) {
            lblTamaSceltoIcon.setIcon(new ImageIcon("src/it/iis/tama/assets/TamaMorto96.png"));
        }
        if (iniziale) {
            return;
        }
        if (tama.infelice()) {
            scrittore.scrivi(tama.getNome() + " è triste!");
        }
        if (tama.morto()) {
            scrittore.scrivi(tama.getNome() + " è morto!");
        }
        listener.cambioStato();
    }

    private void aggiornaProgressBar(JProgressBar progressBar, int valore) {
        progressBar.setValue(valore);
        if (valore < 0.15 * progressBar.getMaximum()) {
            progressBar.setForeground(Colore.FRENCH_PINK);
        } else if (valore < 0.5 * progressBar.getMaximum()) {
            progressBar.setForeground(Colore.LOVE_FUMES);
        } else {
            progressBar.setForeground(Colore.LUNATIC_SKY_DANCER);
        }
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        int valore = (int) evt.getNewValue();
        switch (evt.getPropertyName()) {
            case Tamagotchi.PROP_AFFETTO ->
                aggiornaAffetto(valore);
            case Tamagotchi.PROP_SAZIETA ->
                aggiornaSazieta(valore);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeTama = new javax.swing.JLabel();
        barSazieta = new javax.swing.JProgressBar();
        barAffetto = new javax.swing.JProgressBar();
        btnDaiBiscotti = new javax.swing.JButton();
        btnDaiCarezze = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAffetto = new javax.swing.JLabel();
        lblSazieta = new javax.swing.JLabel();
        lblTamaSceltoIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sliderQuantita = new javax.swing.JSlider();
        lblQuantita = new javax.swing.JLabel();
        lblTriste = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 246, 224));
        setMaximumSize(new java.awt.Dimension(230, 400));
        setMinimumSize(new java.awt.Dimension(230, 400));
        setPreferredSize(new java.awt.Dimension(230, 400));

        lblNomeTama.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lblNomeTama.setForeground(new java.awt.Color(255, 99, 162));
        lblNomeTama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeTama.setText("Nome Tama");

        barSazieta.setBackground(new java.awt.Color(112, 116, 157));
        barSazieta.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        barSazieta.setForeground(new java.awt.Color(107, 255, 164));
        barSazieta.setValue(50);
        barSazieta.setBorderPainted(false);
        barSazieta.setFocusable(false);

        barAffetto.setBackground(new java.awt.Color(112, 116, 157));
        barAffetto.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        barAffetto.setForeground(new java.awt.Color(107, 255, 164));
        barAffetto.setValue(50);
        barAffetto.setBorderPainted(false);
        barAffetto.setFocusable(false);

        btnDaiBiscotti.setBackground(new java.awt.Color(255, 206, 209));
        btnDaiBiscotti.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btnDaiBiscotti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/iis/tama/assets/biscotto.png"))); // NOI18N
        btnDaiBiscotti.setBorderPainted(false);
        btnDaiBiscotti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaiBiscotti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaiBiscottiActionPerformed(evt);
            }
        });

        btnDaiCarezze.setBackground(new java.awt.Color(255, 206, 209));
        btnDaiCarezze.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btnDaiCarezze.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/iis/tama/assets/affetto.png"))); // NOI18N
        btnDaiCarezze.setBorderPainted(false);
        btnDaiCarezze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaiCarezze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaiCarezzeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Dai biscotti");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel2.setText("Dai carezze");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel3.setText("Quantità");

        lblAffetto.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblAffetto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAffetto.setText("0");

        lblSazieta.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblSazieta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSazieta.setText("0");

        lblTamaSceltoIcon.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblTamaSceltoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/iis/tama/assets/Tamagotchi96.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/iis/tama/assets/affetto16.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/iis/tama/assets/biscotto16.png"))); // NOI18N

        sliderQuantita.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        sliderQuantita.setForeground(new java.awt.Color(255, 99, 162));
        sliderQuantita.setMaximum(10);
        sliderQuantita.setMinimum(1);
        sliderQuantita.setValue(1);
        sliderQuantita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sliderQuantita.setFocusable(false);
        sliderQuantita.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderQuantitaMouseDragged(evt);
            }
        });

        lblQuantita.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblQuantita.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblQuantita.setText("1");
        lblQuantita.setToolTipText("");

        lblTriste.setBackground(new java.awt.Color(255, 99, 162));
        lblTriste.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        lblTriste.setForeground(new java.awt.Color(255, 255, 255));
        lblTriste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTriste.setText("!");
        lblTriste.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblTamaSceltoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTriste, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDaiBiscotti, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDaiCarezze, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(lblQuantita, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(sliderQuantita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(barSazieta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(barAffetto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAffetto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSazieta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNomeTama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTamaSceltoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTriste))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeTama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(barAffetto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAffetto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barSazieta, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSazieta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDaiBiscotti)
                    .addComponent(btnDaiCarezze))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantita)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addComponent(sliderQuantita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDaiBiscottiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaiBiscottiActionPerformed
        int quantita = sliderQuantita.getValue();
        scrittore.scrivi(tama.getNome() + " mangia " + quantita + " biscott" + (quantita > 1 ? "i" : "o"));
        tama.daiBiscotti(quantita);
        aggiornaStato(false);
    }//GEN-LAST:event_btnDaiBiscottiActionPerformed

    private void btnDaiCarezzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaiCarezzeActionPerformed
        int quantita = sliderQuantita.getValue();
        scrittore.scrivi(tama.getNome() + " riceve " + quantita + " carezz" + (quantita > 1 ? "e" : "a"));
        tama.daiCarezze(quantita);
        aggiornaStato(false);
    }//GEN-LAST:event_btnDaiCarezzeActionPerformed

    private void sliderQuantitaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderQuantitaMouseDragged
        lblQuantita.setText(String.valueOf(sliderQuantita.getValue()));
    }//GEN-LAST:event_sliderQuantitaMouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barAffetto;
    private javax.swing.JProgressBar barSazieta;
    private javax.swing.JButton btnDaiBiscotti;
    private javax.swing.JButton btnDaiCarezze;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAffetto;
    private javax.swing.JLabel lblNomeTama;
    private javax.swing.JLabel lblQuantita;
    private javax.swing.JLabel lblSazieta;
    private javax.swing.JLabel lblTamaSceltoIcon;
    private javax.swing.JLabel lblTriste;
    private javax.swing.JSlider sliderQuantita;
    // End of variables declaration//GEN-END:variables

}
